### ISSUE TITLE
ko.execute can use ko.pureComputed internally

### ISSUE THREAD

**Issue by mbest** [danielearwicker/knockout.clear#1]
If you use `ko.pureComputed` within `ko.execute`, you can optimize the code in a few ways:
1. Rather than returning a "pseudoComputed", you can return the real computed. You won't have to keep track of extenders.
2. The "wake" function just needs to create a manual subscription on the internal pureComputed to awaken it.
3. The internal pureComputed will only call the `evaluator` if any dependencies have changed, even when awakening, possibly avoiding unnecessary AJAX calls.

**Comment by danielearwicker** [comment]
So there will not be creating disposing of a ko.computed, just calling subscribe on the pre-existing pureComputed, stashing the subscription object and then disposing it.

That's excellent, will try it with my codebase ASAP and then update.

**Comment by danielearwicker** [comment]
Perfect!
